baseurl = "https://grantcooksey.github.io/MyersSportsMedicine"
languageCode = "en-us"
title = "Myers Sports Medicine & Orthopaedic Center"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
enableRobotsTXT = true
relativeurls = true

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

# About ---------------------

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 2

[[menu.main]]
    name = "About Us"
    url = "about/"
    parent = "about"
    weight = 1

[[menu.main]]
    name = "Meet Dr. Myers"
    url = "dr-myers/"
    parent = "about"
    weight = 2

[[menu.main]]
    name = "Staff Bios"
    url = "staff-bios/"
    parent = "about"
    weight = 3

[[menu.main]]
    name = "Staff Bios"
    url = "staff-bios/"
    parent = "about"
    weight = 4

# Patient Info ----------------------

[[menu.main]]
    name = "Patient Info"
    identifier = "info"
    weight = 3

[[menu.main]]
    name = "Patient Forms"
    url = "patient-info/"
    parent = "info"
    weight = 1

[[menu.main]]
    name = "Insurance"
    url = "insurance/"
    parent = "info"
    weight = 2

[[menu.main]]
    name = "Concierge Service"
    url = "patient-info/concierge-service/"
    parent = "info"
    weight = 3

# Patient Education ---------------------

[[menu.main]]
    name = "Patient Education"
    identifier = "edu"
    weight = 4

[[menu.main]]
    name = "Patient Education"
    url = "patient-education/"
    parent = "edu"
    weight = 1

[[menu.main]]
    name = "The Knee"
    url = "the-knee/"
    parent = "edu"
    weight = 2

[[menu.main]]
    name = "The Shoulder"
    url = "the-shoulder/"
    parent = "edu"
    weight = 3

[[menu.main]]
    name = "Sports Medicine"
    url = "sports-medicine/"
    parent = "edu"
    weight = 4

[[menu.main]]
    name = "Featured Procedures"
    url = "procedures/"
    parent = "edu"
    weight = 5

# Testimonials ------------------

[[menu.main]]
    name = "Testimonials"
    url = "testimonials/"
    weight = 5

[Params]
    defaultImageLarge = "images/featured-images/workout-min.jpg"
    defaultImageSmall = "images/featured-images/operating-min.jpg"
    logo = "images/logo.jpg"
    contactImg = "images/about/office.jpg"
